import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { BackgroundElement } from "./page";
import bgParams from "./background.json";

const bebasNeue = localFont({
  src: "../public/bebas_neue.ttf",
  display: "swap",
  variable: "--font-bebas-nue",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${interSans.variable} ${bebasNeue.variable} bg-background antialiased h-full`}
    >
      <body className="relative h-screen grid place-items-center">
        {/* <div className="overflow-auto h-full py-(--frame-height) px-(--frame-width)"> */}
        <div className="overflow-auto scrollbar-track-background scrollbar-thumb-neutral-200 dark:scrollbar-thumb-neutral-800 scrollbar-thin h-[calc(100%-var(--frame-height)*2)] w-[calc(100%-var(--frame-width)*2)]">
          {children}
        </div>
        {/* <div className="z-10 bg-background w-(--frame-width) fixed left-0 top-0 bottom-0"></div>
        <div className="z-10 bg-background w-(--frame-width) fixed right-0 top-0 bottom-0"></div>
        <div className="z-10 bg-background h-(--frame-height) fixed left-0 top-0 right-0"></div>
        <div className="z-10 bg-background h-(--frame-height) fixed left-0 bottom-0 right-0"></div> */}
        <div className="z-10 bg-drawing w-px fixed left-(--frame-width) top-0 bottom-0"></div>
        <div className="z-10 bg-drawing w-px fixed right-(--frame-width) top-0 bottom-0"></div>
        <div className="z-10 bg-drawing h-px fixed left-0 right-0 top-(--frame-height)"></div>
        <div className="z-10 bg-drawing h-px fixed left-0 right-0 bottom-(--frame-height)"></div>
        {/* </div> */}
      </body>
    </html>
  );
}
